name: flutter_hardcode_localizer
description: A Dart plugin that finds hardcoded strings in Flutter projects and provides quick-fix to move them to localization files for easy_localization.
version: 1.0.7
homepage: https://github.com/AshishPatel2611/flutter_hardcode_localizer

environment:
  sdk: ">=3.6.2 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  analyzer: ^7.6.0
  custom_lint_builder: ^0.8.0
  dart_style: ^3.1.1

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0

executables:
  localize: localize