name: example_flutter_project  
description: Example Flutter project to test hardcode localizer v1.0.1 with easy_localization

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_hardcode_localizer:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/languages/